image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:30-${DOCKER_IMAGE_VERSION}

cache:
  paths:
    - cache/

stages:
  - test
  - docs
  - upload

before_script:
  # Diagnostics
  - mount
  - df -h

  - useradd -Um buildstream
  - chown -R buildstream:buildstream .

variables:
  # Version of the docker images we should use for all the images.
  # This is taken from buildstream/buildstream-docker-images and is updated
  # periodically.
  DOCKER_IMAGE_VERSION: master-106676842

#####################################################
#                    Test stage                     #
#####################################################

.test-template: &test-template
  stage: test
  variables: &test-variables
    PYTEST_ADDOPTS: "--color=yes"
  script:
    - export INTEGRATION_CACHE="$(pwd)/cache/integration-cache"

    - chown -R buildstream:buildstream .

    # Run the tests form the source distribution.
    # We run as a simple user to test for permission issues
    - su buildstream -c 'tox -- --integration'

test-fixed-debian-9:
  <<: *test-template
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-debian:9-${DOCKER_IMAGE_VERSION}
  variables:
    <<: *test-variables
    TOXENV: "py35-bst-fixed"

test-fixed-ubuntu-18:
  <<: *test-template
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-ubuntu:18.04-${DOCKER_IMAGE_VERSION}
  variables:
    <<: *test-variables
    TOXENV: "py36-bst-fixed"

test-fixed-fedora-30:
  <<: *test-template
  variables:
    <<: *test-variables
    TOXENV: "py37-bst-fixed"

test-fixed-python-38-debian:
  <<: *test-template
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-python:3.8-buster-${DOCKER_IMAGE_VERSION}
  variables:
    <<: *test-variables
    TOXENV: "py38-bst-fixed"

# NOTE: Tests against master are only run against only one distribution in
# order to conserve CI resources.
test-master-fedora-30:
  image: registry.gitlab.com/buildstream/buildstream-docker-images/testsuite-fedora:31-${DOCKER_IMAGE_VERSION}
  <<: *test-template
  variables:
    <<: *test-variables
    TOXENV: "py37-bst-master"
  allow_failure: true

lint:
  stage: test
  script:
  - tox -e lint

format-check:
  stage: test
  script:
  - tox -e format-check

# Automatically build documentation, only for merges which land
# on master branch.
#
# Note: We still do not enforce a consistent installation of python2
#       or sphinx, as python2 will significantly grow the backing image.
#

#####################################################
#                  Docs stage                       #
#####################################################

pages:
  stage: docs
  script:
  - dnf install -y python2 make
  # Pin sphinx as docs will not build at latest version
  - pip3 install sphinx==1.8.5
  - pip3 install sphinx-click
  # Pin sphinx_rtd_theme because search functionality breaks
  # at the latest version
  - pip3 install sphinx_rtd_theme>=0.4.2
  - pip3 install --user .
  - make -C doc
  - mv doc/build/html public
  artifacts:
    paths:
    - public/
  only:
  - master


# Automatically upload to PyPI when a release is tagged.

#####################################################
#               Upload stage                        #
#####################################################

upload:
  stage: upload
  before_script:
  - pip3 install twine
  script:
  - python3 setup.py sdist
  - twine upload dist/*.tar.gz
  only:
  - /[0-9]+\.[0-9]+\.[0-9]+/
  except:
  - branches
